In [1]:
import os
import pandas as pd

In [2]:
df = pd.read_csv('t16.csv', sep = ',')

In [3]:
df['jjmmaa'] = pd.to_datetime(df['jjmmaa'])

In [4]:
df

,rgs,pr,m,js,jjmmaa,hhmm,Vitesse,To,Qualite,Q,A,Code
0,101#M1a,0,430,Ve,2016-01-01,00:00,92.0,1.0,?,421.0,101,M1a
1,102#M1b,1,9,Ve,2016-01-01,00:00,92.0,3.0,,835.0,102,M1b
2,103#M1c,1,508,Ve,2016-01-01,00:00,0.0,0.0,,0.0,103,M1c
3,104#M1d,2,30,Ve,2016-01-01,00:00,92.0,3.0,,792.0,104,M1d
4,105#M1e,2,462,Ve,2016-01-01,00:00,91.0,3.0,,842.0,105,M1e
5,106#M1f,3,2,Ve,2016-01-01,00:00,98.0,1.0,,468.0,106,M1f
6,107#M1g,3,507,Ve,2016-01-01,00:00,95.0,2.0,,478.0,107,M1g
7,108#M1h,4,96,Ve,2016-01-01,00:00,0.0,0.0,,0.0,108,M1h
8,109#M1i,4,593,Ve,2016-01-01,00:00,96.0,2.0,,579.0,109,M1i
9,110#M1j,5,275,Ve,2016-01-01,00:00,99.0,1.0,?,294.0,110,M1j
10,112#M1l,6,140,Ve,2016-01-01,00:00,94.0,1.0,?,262.0,112,M1l
11,113#M1m,6,950,Ve,2016-01-01,00:00,0.0,0.0,?,0.0,113,M1m
12,115#M1o,7,961,Ve,2016-01-01,00:00,100.0,1.0,?,249.0,115,M1o
13,117#M1q,8,849,Ve,2016-01-01,00:00,99.0,1.0,?,254.0,117,M1q
14,119#M1s,9,817,Ve,2016-01-01,00:00,92.0,1.0,,308.0,119,M1s
15,121#m1f,3,12,Ve,2016-01-01,00:00,0.0,0.0,,0.0,121,m1f
16,122#m1g,3,517,Ve,2016-01-01,00:00,0.0,0.0,,0.0,122,m1g
17,125#M1y,12,886,Ve,2016-01-01,00:00,97.0,1.0,,393.0,125,M1y
18,126#mbg,3,507,Ve,2016-01-01,00:00,0.0,0.0,,0.0,126,mbg
19,127#mbf,3,2,Ve,2016-01-01,00:00,0.0,0.0,,0.0,127,mbf
20,128#mbe,2,462,Ve,2016-01-01,00:00,0.0,0.0,,1.0,128,mbe
21,151#M1A,0,430,Ve,2016-01-01,00:00,93.0,1.0,?,409.0,151,M1A
22,152#M1B,1,9,Ve,2016-01-01,00:00,93.0,2.0,,587.0,152,M1B
23,153#M1C,1,508,Ve,2016-01-01,00:00,96.0,3.0,,870.0,153,M1C
24,154#M1D,2,30,Ve,2016-01-01,00:00,99.0,3.0,,858.0,154,M1D
25,155#M1E,2,462,Ve,2016-01-01,00:00,0.0,0.0,,0.0,155,M1E
26,156#M1F,3,2,Ve,2016-01-01,00:00,93.0,2.0,,629.0,156,M1F
27,157#M1G,3,507,Ve,2016-01-01,00:00,83.0,4.0,,845.0,157,M1G
28,158#M1H,4,96,Ve,2016-01-01,00:00,0.0,0.0,,0.0,158,M1H
29,159#M1I,4,593,Ve,2016-01-01,00:00,94.0,3.0,,849.0,159,M1I
...,...,...,...,...,...,...,...,...,...,...,...,...
1048545,808#M8h,275,695,Di,2016-07-17,21:00,0.0,0.0,,0.0,808,M8h
1048546,809#M8i,276,238,Di,2016-07-17,21:00,88.0,9.0,,2347.0,809,M8i
1048547,810#M8j,276,726,Di,2016-07-17,21:00,81.0,4.0,,976.0,810,M8j
1048548,811#M8k,277,278,Di,2016-07-17,21:00,88.0,5.0,,1542.0,811,M8k
1048549,812#M8l,277,925,Di,2016-07-17,21:00,0.0,0.0,,0.0,812,M8l
1048550,813#M8m,278,360,Di,2016-07-17,21:00,0.0,0.0,,0.0,813,M8m
1048551,814#M8n,279,86,Di,2016-07-17,21:00,79.0,8.0,,1922.0,814,M8n
1048552,815#M8o,279,614,Di,2016-07-17,21:00,0.0,0.0,,0.0,815,M8o
1048553,816#M8p,280,165,Di,2016-07-17,21:00,0.0,0.0,,0.0,816,M8p
1048554,817#m8p,280,165,Di,2016-07-17,21:00,0.0,0.0,,0.0,817,m8p
1048555,818#M8r,281,0,Di,2016-07-17,21:00,0.0,0.0,,0.0,818,M8r
1048556,819#M8s,281,700,Di,2016-07-17,21:00,0.0,0.0,,0.0,819,M8s
1048557,851#M8A,271,850,Di,2016-07-17,21:00,54.0,32.0,,3426.0,851,M8A
1048558,852#M8B,272,375,Di,2016-07-17,21:00,65.0,21.0,,2935.0,852,M8B
1048559,853#M8C,272,860,Di,2016-07-17,21:00,0.0,0.0,,0.0,853,M8C
1048560,854#M8D,273,440,Di,2016-07-17,21:00,74.0,23.0,,4218.0,854,M8D
1048561,855#M8E,273,900,Di,2016-07-17,21:00,79.0,23.0,,4780.0,855,M8E
1048562,856#M8F,274,450,Di,2016-07-17,21:00,83.0,18.0,,4237.0,856,M8F
1048563,857#M8G,275,90,Di,2016-07-17,21:00,88.0,20.0,,4267.0,857,M8G
1048564,858#M8H,275,695,Di,2016-07-17,21:00,0.0,0.0,,0.0,858,M8H
1048565,859#M8I,276,238,Di,2016-07-17,21:00,85.0,19.0,,4138.0,859,M8I
1048566,860#M8J,276,726,Di,2016-07-17,21:00,79.0,23.0,,4427.0,860,M8J
1048567,861#M8K,277,278,Di,2016-07-17,21:00,64.0,10.0,,1655.0,861,M8K
1048568,862#M8L,277,877,Di,2016-07-17,21:00,0.0,0.0,,0.0,862,M8L
1048569,863#M8M,278,360,Di,2016-07-17,21:00,0.0,0.0,,0.0,863,M8M
1048570,864#M8N,279,86,Di,2016-07-17,21:00,73.0,9.0,?,1852.0,864,M8N
1048571,865#M8O,279,614,Di,2016-07-17,21:00,0.0,0.0,?,0.0,865,M8O
1048572,866#M8P,280,350,Di,2016-07-17,21:00,0.0,0.0,?,0.0,866,M8P
1048573,867#M8Q,280,360,Di,2016-07-17,21:00,0.0,0.0,?,0.0,867,M8Q
1048574,868#M8R,281,0,Di,2016-07-17,21:00,0.0,0.0,?,0.0,868,M8R

In [4]:
#selectionner les donnees du 15 juillet jusqu'a 
select = df[(df['jjmmaa'] > '2016-07-15') & (df['jjmmaa'] <= '2016-08-30')]

In [5]:
# Reindexer La table
select.index = range(len(select))

In [6]:
select.head()

,rgs,pr,m,js,jjmmaa,hhmm,Vitesse,To,Qualite,Q,A,Code
0,101#M1a,0,430,Ve,2016-08-01,00:00,94.0,2.0,?,488.0,101,M1a
1,102#M1b,1,9,Ve,2016-08-01,00:00,95.0,3.0,,845.0,102,M1b
2,103#M1c,1,508,Ve,2016-08-01,00:00,0.0,0.0,,0.0,103,M1c
3,104#M1d,2,30,Ve,2016-08-01,00:00,96.0,3.0,,805.0,104,M1d
4,105#M1e,2,462,Ve,2016-08-01,00:00,95.0,3.0,,840.0,105,M1e

In [7]:
# L'heure de pointe du matin de 7.30 a 9h
cond1 = df.apply ( lambda row : row["hhmm"] > '07:54', axis = 1 )
cond2 = df.apply ( lambda row : row["hhmm"] < '09:06', axis = 1 )
# L'intersection des deux condition.
df1 = pd.merge(df[cond1], df[cond2], how='inner')

In [8]:
# de 9h a 10h
cond1 = df.apply ( lambda row : row["hhmm"] > '08:54', axis = 1 )
cond2 = df.apply ( lambda row : row["hhmm"] < '10:06', axis = 1 )
# L'intersection des deux condition.
df2 = pd.merge(df[cond1], df[cond2], how='inner')

In [9]:
# L'heure de pointe du matin
cond1 = df.apply ( lambda row : row["hhmm"] > '11:54', axis = 1 )
cond2 = df.apply ( lambda row : row["hhmm"] < '13:06', axis = 1 )
# L'intersection des deux condition.
df3 = pd.merge(df[cond1], df[cond2], how='inner')

In [10]:
# L'heure de pointe du Soir de 17 a 19
cond1 = df.apply ( lambda row : row["hhmm"] > '17:00', axis = 1 )
cond2 = df.apply ( lambda row : row["hhmm"] < '19:06', axis = 1 )
# L'intersection des deux condition.
df4 = pd.merge(df[cond1], df[cond2], how='inner')

In [11]:
vitesse_8_9 = df1[['Code','Vitesse','Q']].groupby('Code').mean()
vitesse_9_10 = df2[['Code','Vitesse','Q']].groupby('Code').mean()
vitesse_12_13 = df3[['Code','Vitesse','Q']].groupby('Code').mean()
vitesse_17_19 = df4[['Code','Vitesse','Q']].groupby('Code').mean()

In [12]:
VQ = pd.concat([vitesse_8_9,vitesse_9_10,vitesse_12_13,vitesse_17_19], axis = 1)

In [13]:
VQ.columns = ['V_8_9','Q_8_9','V_9_10','Q_9_10','V_12_13','Q_12_13','V_17_19','Q_17_19']

In [14]:
VQ['Code'] = VQ.index

In [15]:
VQ.index = range(len(VQ))

In [16]:
VQ['Code'] = VQ['Code'].astype(str)
VQ['V_8_9'] = VQ['V_8_9'].astype(str)
VQ['Q_8_9'] = VQ['Q_8_9'].astype(str)
VQ['V_9_10'] = VQ['V_9_10'].astype(str)
VQ['Q_9_10'] = VQ['Q_9_10'].astype(str)
VQ['V_12_13'] = VQ['V_12_13'].astype(str)
VQ['Q_12_13'] = VQ['Q_12_13'].astype(str)
VQ['V_17_19'] = VQ['V_17_19'].astype(str)
VQ['Q_17_19'] = VQ['Q_17_19'].astype(str)

In [17]:
VQ['V8_9'] = VQ['Code'] + ' - ' + VQ['V_8_9']
VQ['Q8_9'] = VQ['Code'] + ' - ' + VQ['Q_8_9']
VQ['V9_10'] = VQ['Code'] + ' - ' + VQ['V_9_10']
VQ['Q9_10'] = VQ['Code'] + ' - ' + VQ['Q_9_10']
VQ['V12_13'] = VQ['Code'] + ' - ' + VQ['V_12_13']
VQ['Q12_13'] = VQ['Code'] + ' - ' + VQ['Q_12_13']
VQ['V17_19'] = VQ['Code'] + ' - ' + VQ['V_17_19']
VQ['Q17_19'] = VQ['Code'] + ' - ' + VQ['Q_17_19']

In [19]:
# Supprimer les premieres colonnes
liste = ['V_8_9','Q_8_9','V_9_10','Q_9_10','V_12_13','Q_12_13','V_17_19','Q_17_19']
VQ = VQ.drop(liste, 1,errors='ignore')

In [20]:
VQ.head()

,Code,V8_9,Q8_9,V9_10,Q9_10,V12_13,Q12_13,V17_19,Q17_19
0,M1A,M1A - 89.128,M1A - 1856.4293333333333,M1A - 89.6086956521739,M1A - 1801.7826086956522,M1A - 91.93386243386243,M1A - 1883.3968253968253,M1A - 85.65675675675676,M1A - 2293.6945945945945
1,M1B,M1B - 89.0,M1B - 2188.296,M1B - 89.85054347826087,M1B - 2167.820652173913,M1B - 90.92857142857143,M1B - 2291.2169312169312,M1B - 85.38378378378378,M1B - 2714.0135135135133
2,M1C,M1C - 89.52,M1C - 3814.696,M1C - 90.26902173913044,M1C - 3799.646739130435,M1C - 91.12433862433862,M1C - 4024.862433862434,M1C - 84.7945945945946,M1C - 4967.664864864865
3,M1D,M1D - 92.904,M1D - 3701.3813333333333,M1D - 93.13315217391305,M1D - 3661.907608695652,M1D - 93.14021164021165,M1D - 3883.4285714285716,M1D - 86.51621621621622,M1D - 4819.275675675675
4,M1E,M1E - 0.0,M1E - 0.0,M1E - 0.0,M1E - 0.0,M1E - 0.0,M1E - 0.0,M1E - 0.0,M1E - 0.0

In [21]:
# table isidor
df_isidor = pd.read_csv("table3.csv",header=None, sep = ';')
# renommer la colonne 
df_isidor.columns = ['Code']
# renommer qlq stations
df_isidor['Code'] = df_isidor['Code'].str.replace('MM713.','M7')
df_isidor['Code'] = df_isidor['Code'].str.replace('MM613.','M6')
df_isidor['Code'] = df_isidor['Code'].str.replace('MM513.','M5')
df_isidor['Code'] = df_isidor['Code'].str.replace('MM413.','M4')
df_isidor['Code'] = df_isidor['Code'].str.replace('MM113.','M1')

In [22]:
#L'union Left
result = pd.merge(df_isidor, VQ, how = 'left')

In [23]:
len(result) == len(df_isidor)

True

In [25]:
# Exporter la table
result.to_csv('VQ_ete2.csv', index = False, encoding = 'utf-8')

235